# Generated by Django 3.2 on 2022-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('EID', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
